spring:
  application:
    name: config-server

  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/deadzq/config-server-properties
          search-paths: test1
          username: deadzq
          password: junjun2016

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/